#!/usr/bin/env python3
r'''
Python 语言参考手册
本参考手册介绍了 Python 句法与“核心语义”。在力求简明扼要的同时，我们也尽量做到准确、完整。
    有关内置对象类型、内置函数、模块的语义在 Python 标准库 中介绍。
    有关本语言的非正式介绍，请参阅 Python 教程 。
    对于 C 或 C++ 程序员，我们还提供了两个手册：
        扩展和嵌入 Python 解释器介绍了如何编写 Python 扩展模块，
        Python/C API 参考手册 则详细介绍了 C/C++ 的可用接口。

1. 概述       Introduction
1.1. 其他实现   Alternate Implementations
1.2. 标注     Notation

2. 词法分析     Lexical analysis
2.1. 行结构    Line structure
2.2. 其他形符  Other tokens
2.3. 标识符和关键字    Identifiers and keywords
2.4. 字面值    Literals
2.5. 运算符    Operators
2.6. 分隔符    Delimiters

3. 数据模型     Data model
3.1. 对象、值与类型    Objects, values and types
3.2. 标准类型层级结构   The standard type hierarchy
3.3. 特殊方法名称     Special method names
3.4. 协程         Coroutines

3. 数据模型     Data model
中文：
https://docs.python.org/zh-cn/3/reference/datamodel.html
英文：
https://docs.python.org/3/reference/datamodel.html


4. 执行模型     Execution model
4.1. 程序的结构  Structure of a program
4.2. 命名与绑定  Naming and binding
4.3. 异常     Exceptions

5. 导入系统     The import system
5.1. importlib  importlib
5.2. 包      Packages
5.3. 搜索     Searching
5.4. 加载     Loading
5.5. 基于路径的查找器   The Path Based Finder
5.6. 替换标准导入系统   Replacing the standard import system
5.7. 包相对导入      Package Relative Imports
5.8. 有关 __main__ 的特殊事项  Special considerations for __main__
5.9. 参考文献   References

6. 表达式  Expressions
6.1. 算术转换   Arithmetic conversions
6.2. 原子     Atoms
6.3. 原型     Primaries
6.4. await 表达式  Await expression
6.5. 幂运算符   The power operator
6.6. 一元算术和位运算   Unary arithmetic and bitwise operations
6.7. 二元算术运算符    Binary arithmetic operations
6.8. 移位运算   Shifting operations
6.9. 二元位运算  Binary bitwise operations
6.10. 比较运算  Comparisons
6.11. 布尔运算  Boolean operations
6.12. 赋值表达式     Assignment expressions
6.13. 条件表达式     Conditional expressions
6.14. lambda 表达式    Lambdas
6.15. 表达式列表     Expression lists
6.16. 求值顺序  Evaluation order
6.17. 运算符优先级    Operator precedence

7. 简单语句     Simple statements
7.1. 表达式语句  Expression statements
7.2. 赋值语句   Assignment statements
7.3. assert 语句  The assert statement
7.4. pass 语句    The pass statement
7.5. del 语句     The del statement
7.6. return 语句  The return statement
7.7. yield 语句   The yield statement
7.8. raise 语句   The raise statement
7.9. break 语句   The break statement
7.10. continue 语句   The continue statement
7.11. import 语句     The import statement
7.12. global 语句     The global statement
7.13. nonlocal 语句   The nonlocal statement

8. 复合语句     Compound statements
8.1. if 语句  The if statement
8.2. while 语句   The while statement
8.3. for 语句     The for statement
8.4. try 语句     The try statement
8.5. with 语句    The with statement
8.6. match 语句   The match statement
8.7. 函数定义   Function definitions
8.8. 类定义    Class definitions
8.9. 协程     Coroutines

9. 顶级组件     Top-level components
9.1. 完整的 Python 程序  Complete Python programs
9.2. 文件输入   File input
9.3. 交互式输入  Interactive input
9.4. 表达式输入  Expression input
10. 完整的语法规范     Full Grammar specification

=======================
# Python的实现
    
CPython
    这是 Python 的原始且维护最多的实现，用 C 编写。新的语言功能通常首先出现在此处。

Jython
    Python 用 Java 实现。此实现可以用作 Java 应用程序的脚本语言，也可以用于使用 Java 类库创建应用程序。
    它还经常用于为 Java 库创建测试。更多信息可以在 Jython 网站上找到。
    https://www.jython.org/

Python for .NET
    此实现实际上使用 CPython 实现，但它是一个托管 .NET 应用程序，并且使 .NET 库可用。
    它是由布莱恩·劳埃德创建的。有关详细信息，请参阅 Python for .NET 主页。
    https://pythonnet.github.io/

IronPython 铁蟒
    .NET 的替代 Python。与 Python.NET 不同，这是一个完整的 Python 实现，可生成 IL，
        并将 Python 代码直接编译为 .NET 程序集。它是由 Jython 的原始创建者 Jim Hugunin 创建的。
        有关更多信息，请参阅 IronPython 网站。
        https://ironpython.net/

PyPy
    完全用 Python 编写的 Python 实现。它支持其他实现中没有的多种高级功能，例如无堆栈支持和即时编译器。
    该项目的目标之一是通过更容易地修改解释器（因为它是用 Python 编写的）来鼓励对语言本身进行实验。
    更多信息可在 PyPy 项目的主页上找到。
    https://www.pypy.org/

Even though the notation used is almost the same, 
there is a big difference between the meaning of lexical and syntactic definitions: 
    a lexical definition operates on the individual characters of the input source, 
    while a syntax definition operates on the stream of tokens generated by the lexical analysis. 
    All uses of BNF in the next chapter (“Lexical Analysis”) are lexical definitions; 
    uses in subsequent chapters are syntactic definitions.
尽管使用的符号几乎相同，但词法定义和句法定义的含义之间存在很大差异：
    词法定义对输入源的各个字符进行操作，而语法定义对由输入源生成的标记流进行操作。
    词法分析。下一章（“词法分析”）中所有 BNF 的使用都是词法定义；后续章节中使用的是语法定义。

词法：lexical
语法：syntax

''' 


if __name__ == '__main__':
    print(__doc__)
    def test():
        print('Reference.py')
    test()